In [2]:
import pandas as pd

In [3]:
pd.DataFrame({'Yes':[50,21],'No':[131,2]})

   Yes   No
0   50  131
1   21    2

In [4]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']})

             Bob           Sue
0    I liked it.  Pretty good.
1  It was awful.        Bland.

In [5]:
pd.Series([30,25,40],index=['2015 sales','2020 sales','2025 sales'], name='Product A')

2015 sales    30
2020 sales    25
2025 sales    40
Name: Product A, dtype: int64

SyntaxError: invalid syntax (1933637684.py, line 1)

In [15]:
file_path.shape

AttributeError: 'str' object has no attribute 'shape'